Fix `CompileCache::YAML` cache options mutation & `symbolize_{keys,names}`
during cache miss (when an entry for a YAML file exists, but is not usable e.g. due to safety mismatch)
the `storage_to_output` is hit; it mutates `kwargs`, replacing `symbolize_names` with
`symbolize_keys`, which is not supported by edge `psych`.

```shell
1) Error:
CompileCacheYAMLTest#test_load_file_symbolize_names_after_unsafe_cache:
ArgumentError: unknown keyword: :symbolize_keys
    ~/.asdf/installs/ruby/4.0.5/lib/ruby/4.0.0/psych.rb:369:in 'Psych.load'
    lib/bootsnap/compile_cache/yaml.rb:220:in 'Bootsnap::CompileCache::YAML::Psych4::SafeLoad#input_to_output'
    lib/bootsnap/compile_cache/yaml.rb:235:in 'Bootsnap::CompileCache::Native.fetch'
    lib/bootsnap/compile_cache/yaml.rb:235:in 'Bootsnap::CompileCache::YAML::Psych4::Patch#load_file'
    test/compile_cache/yaml_test.rb:165:in 'block in CompileCacheYAMLTest#test_load_file_symbolize_names_after_unsafe_cache'
    test/compile_cache/yaml_test.rb:164:in 'Integer#times'
    test/compile_cache/yaml_test.rb:164:in 'CompileCacheYAMLTest#test_load_file_symbolize_names_after_unsafe_cache'
```